remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
title: FOX-CARZ Documentation
description: Documentation for the FOX-CARZ car rental platform
show_downloads: true
google_analytics:
theme: jekyll-theme-cayman